"""Add keyword_id to SearchResult

Revision ID: 700f1eebf919
Revises: 
Create Date: 2025-06-29 18:11:37.521238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700f1eebf919'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'keyword', ['keyword_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('keyword_id')

    # ### end Alembic commands ###
